{{- if and .Values.monitoring.enabled .Values.monitoring.alerts.enabled }}

{{- if eq .Values.monitoring.engine "prometheus" }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
{{- else if eq .Values.monitoring.engine "victoriametrics" }}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMRule
{{- else }}
    {{- fail "Unexpected monitoring engine: $.Values.monitoring.engine" }}
{{- end }}
metadata:
  name: task-proxy-alerts
  namespace: {{ .Release.Namespace }}
  {{- if eq .Values.monitoring.engine "prometheus" }}
  labels:
    release: prometheus-stack
  {{- end }}
spec:
  groups:
    - name: task-proxy
      rules:
        - alert: TaskProxyAuthorizationInfrastructureFailures
          expr: sum(increase(auth_infra_errors_total[1m])) > {{ .Values.monitoring.alerts.infrastructureAuthFailuresPerMinuteThreshold }}
          labels:
            severity: warning
          annotations:
            summary: Task proxy authorization infrastructure failures exceed threshold
            description: Task proxy observed more than {{ .Values.monitoring.alerts.infrastructureAuthFailuresPerMinuteThreshold }} authorization infrastructure failures over the last minute.
        - alert: TaskProxyAuthorizationContextDeadlineExceeded
          expr: sum(increase(auth_infra_errors_total{kind="context_deadline_exceeded"}[1m])) > {{ .Values.monitoring.alerts.contextDeadlineExceededPerMinuteThreshold }}
          labels:
            severity: warning
          annotations:
            summary: Task proxy authorization context deadline exceeded rate exceeds threshold
            description: Task proxy observed more than {{ .Values.monitoring.alerts.contextDeadlineExceededPerMinuteThreshold }} context deadline exceeded authorization failures over the last minute.
        - alert: TaskProxyAuthorizationGrpcUnavailable
          expr: sum(increase(auth_infra_errors_total{kind="grpc_unavailable"}[1m])) > {{ .Values.monitoring.alerts.grpcUnavailablePerMinuteThreshold }}
          labels:
            severity: warning
          annotations:
            summary: Task proxy authorization gRPC unavailable rate exceeds threshold
            description: Task proxy observed more than {{ .Values.monitoring.alerts.grpcUnavailablePerMinuteThreshold }} gRPC unavailable authorization failures over the last minute.
        - alert: TaskProxyAuthorizationConnectionTimeout
          expr: sum(increase(auth_infra_errors_total{kind="connection_timeout"}[1m])) > {{ .Values.monitoring.alerts.connectionTimeoutPerMinuteThreshold }}
          labels:
            severity: warning
          annotations:
            summary: Task proxy authorization connection timeout rate exceeds threshold
            description: Task proxy observed more than {{ .Values.monitoring.alerts.connectionTimeoutPerMinuteThreshold }} connection timeout authorization failures over the last minute.

{{- end }}
