apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    yt_component: task-proxy
spec:
  type:
  {{- if .Values.tls.enabled }}
    LoadBalancer
  {{- else }}
    NodePort
  {{- end }}
  selector:
    app.kubernetes.io/component: task-proxy
  ports:
  - name: http
    targetPort: 8080
    port:
    {{- if .Values.tls.enabled }}
      443
    {{- else }}
      80
    {{- end }}
  {{- if .Values.monitoring.enabled }}
  - name: metrics
    port: 9102
    targetPort: 9102
  - name: envoy-metrics
    port: 9901
    targetPort: 9901
  {{- end }}
